# Generated by Django 5.2.8 on 2025-11-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_fruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
