# Generated by Django 5.2.8 on 2025-11-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0003_fruit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='description',
            field=models.CharField(),
        ),
    ]
